config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'
  get '/entrar', to: 'sessions#new', as: 'entrar'
  post '/entrar', to: 'sessions#create'
  delete '/sair', to: 'sessions#destroy'

  get '/sobre', to: 'pages#sobre', as: 'sobre'
  get '/contato', to: 'pages#contato', as: 'contato'

  resources :contacts
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze

  validates :name, presence: true, length: { maximum: 50 }
  validates :password, length: { minimum: 6 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: true }

  has_secure_password
  has_many :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  private

  def require_logged_in_user
    unless user_signed_in?
      flash[:danger] = 'Area Restrita. Pro favor faça o login !'
      redirect_to entrar_path
    end
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :require_logged_in_user
  before_action :set_contact, only: %i[show edit update destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = current_user.contacts
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show; end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit; end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = current_user.contacts.build(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_contact
    @contact = current_user.contacts.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def contact_params
    params.require(:contact).permit(:name, :phone)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def sobre
  end

  def contato
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      sign_in(user)
      flash[:notice] = 'Logado com sucesso !'
      redirect_to contacts_path
    else
      flash[:danger] = 'Não foi possivel logar no sistema !'
      render :new
    end
  end

  def destroy
    sign_out
    flash[:notice] = 'Logout com sucesso !'
    redirect_to entrar_path
  end

  private

  def sessions_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_logged_in_user, only: %i[edit update]
  before_action :set_user, only: %i[edit update]

  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new(params_user)
    if @user.save
      flash[:success] = 'Usuário criado com sucesso !'
      redirect_to entrar_path
    else
      flash[:danger] = 'Erro ao criar usuário.'
      render :new
    end
  end

  def update
    if @user.update(params_user)
      flash[:notice] = 'Usuário atualizado com sucesso !'
      redirect_to contacts_path
    else
      flash[:danger] = 'Erro ao atualizar usuário !'
      render :edit
    end
  end

  private

  def params_user
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def flash_class(level)
        case level
            when 'notice' then "alert alert-info"
            when 'success' then "alert alert-success"
            when 'danger' then "alert alert-danger"            
        end
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    session[:user_id] = user.id
  end

  def sign_out
    session.delete(:user_id)
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def user_signed_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
<% if contact.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(contact.errors.count, "error") %>
      prohibited this contact from being saved:</h2>

    <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="form-group">
  <%= form.label :name %>
  <%= form.text_field :name, class:'form-control' %>
</div>

<div class="form-group">
  <%= form.label :phone %>
  <%= form.text_field :phone, class:'form-control' %>
</div>

<div class="form-group">
  <%= form.submit nil, class: 'btn btn-primary'%>
</div>
<% end %>

app/views/contacts/edit.html.erb
<div class="contatiner">
  <div class="row justify-content-center">
    <div class="col-6">
      <h1 class="mt-2 pb-2">Editar Contato</h1>

      <%= render 'form', contact: @contact %>

      <%= link_to 'Show', @contact, class:'btn btn-outline-info btn-sm' %>
      |
      <%= link_to 'Voltar', contacts_path, class:'btn btn-outline-danger btn-sm' %>

    </div>
  </div>
</div>

app/views/contacts/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-sm-8">
      <h1 class="mt-2 pb-2">Lista de Contatos</h1>

      <table class="table table-border table-hover">
        <thead>
          <tr>
            <th>Nome</th>
            <th>Telefone</th>
            <th colspan="3">Ações</th>
          </tr>
        </thead>

        <tbody>
          <% @contacts.each do |contact| %>
            <tr>
              <td><%= contact.name %></td>
              <td><%= contact.phone %></td>
              <td><%= link_to 'Show', contact, class: 'btn btn-outline-info btn-sm' %></td>
              <td><%= link_to 'Editar', edit_contact_path(contact), class: 'btn btn-outline-success btn-sm' %></td>
              <td><%= link_to 'Destruir', contact, method: :delete, class: 'btn btn-outline-danger btn-sm', data: { confirm: 'Apagar contato. Tem certeza?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'Novo Contato', new_contact_path, class: 'btn btn-primary' %>

    </div>
  </div>
</div>

app/views/contacts/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-sm-8">
      <h1 class="mt-2 pb-2">Novo Contato</h1>

      <%= render 'form', contact: @contact %>

      <%= link_to 'Voltar', contacts_path, class: 'btn btn-outline-danger btn-sm' %>
    </div>
  </div>
</div>

app/views/contacts/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-8">
      <div class="jumbotron pt-4 pb-4">
        <h1 class="h3 mt-0 pb-2">Contato</h1>
        <p>
          <strong>Name:</strong>
          <%= @contact.name %>
        </p>

        <p>
          <strong>Phone:</strong>
          <%= @contact.phone %>
        </p>

        <%= link_to 'Editar', edit_contact_path(@contact), class:'btn btn-outline-success btn-sm' %>
        |
        <%= link_to 'Voltar', contacts_path, class:'btn btn-outline-danger btn-sm' %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Contact List</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>      
      <div class="container pt-2">  
        <%= render 'shared/messages' %> 
        
        <%= yield %>

      </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/contato.html.erb
<h1>Pages#contato</h1>
<p>Find me in app/views/pages/contato.html.erb</p>

app/views/pages/index.html.erb
<div class="jumbotron mt-2 pb-2">
  <h1 class="display-3">Bem vindo !</h1>
  <p class="lead">Cadastre-se e gerencie seus contatos !</p>
  <p>
    <%= link_to 'Criar conta', new_user_path, class: 'btn btn-primary' %>
  </p>
</div>

app/views/pages/sobre.html.erb
<h1>Pages#sobre</h1>
<p>Find me in app/views/pages/sobre.html.erb</p>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
            <div class="alert alert-danger" role="alert">
                <h2>Ops foi encontrado <%= pluralize(object.errors.count, "erro","erros") %> </h2>
                <ul>
                    <% object.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                </ul>
            </div>
        <% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
    <span class="text-muted">Lista de Contatos - Desenvolvido por Alef Ojeda de Oliveira &copy; 2018</span>
  </div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Lista de Contatos', root_path, class:'navbar-brand'%>
  <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId" aria-controls="collapsibleNavId" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="collapsibleNavId">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <% if !user_signed_in?%>
        <li class="nav-item active">
          <%= link_to 'Criar conta', new_user_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
    <ul class="navbar-nav float-right">
      <% if !user_signed_in?%>
        <li class="nav-item">
          <%= link_to 'Login', entrar_path, class: 'nav-link'%>
        </li>
      <% else %>
        <!-- Dropdown -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
            Bem vindo,
            <%= current_user.name %>
          </a>
          <div class="dropdown-menu">
            <%= link_to 'Minha Página', contacts_path, class:'dropdown-item' %>
            <%= link_to 'Editar', edit_user_path(current_user), class:'dropdown-item' %>
            <div class="dropdown-divider"></div>
            <%= link_to 'Sair', sair_path, class:'dropdown-item', method: :delete %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/shared/_messages.html.erb
<% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %> alert-dismissable fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
            &times;
        </button>
        
        <%= value %>
    </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, local:true) do |f|%>

<%= render 'shared/error_messages', object: user%>

<div class="form-group">
  <%= f.label :name%>
  <%= f.text_field :name, class: 'form-control'%>
</div>
<div class="form-group">
  <%= f.label :email%>
  <%= f.text_field :email, class: 'form-control'%>
</div>
<div class="form-group">
  <%= f.label :password%>
  <%= f.password_field :password, class: 'form-control'%>
</div>
<div class="form-group">
  <%= f.label :password_confirmation%>
  <%= f.password_field :password_confirmation, class: 'form-control'%>
</div>
<div class="form-group">
  <%= f.submit nil, class: 'btn btn-primary'%>
</div>
<% end %>

app/views/users/edit.html.erb
<div class="container pb-2">
  <div class="row justify-content-center">
    <div class="col-sm-6">
      <h1 class="display-4 mt-2">Editar Conta</h1>
      <%= render 'form', user: @user %>
    </div>
  </div>

</div>

app/views/users/new.html.erb
<div class="container pb-2">
  <div class="row justify-content-center">
    <div class="col-sm-6">
      <h1 class="display-4 mt-2">Criar Conta</h1>
      <%= form_with(model: @user, local:true) do |f|%>

      <%= render 'shared/error_messages', object: @user%>

      <div class="form-group">
        <%= f.label :name%>
        <%= f.text_field :name, class: 'form-control'%>
      </div>
      <div class="form-group">
        <%= f.label :email%>
        <%= f.text_field :email, class: 'form-control'%>
      </div>
      <div class="form-group">
        <%= f.label :password%>
        <%= f.password_field :password, class: 'form-control'%>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation%>
        <%= f.password_field :password_confirmation, class: 'form-control'%>
      </div>
      <div class="form-group">
        <%= f.submit nil, class: 'btn btn-primary'%>

      </div>
    <% end %>
  </div>
</div>

</div>